# Generated by Django 3.1.1 on 2020-10-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=750)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=10)),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Presciption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=750)),
                ('Doctor_name', models.CharField(max_length=750)),
                ('Patient_name', models.CharField(max_length=750)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=70)),
                ('symptoms', models.CharField(max_length=750)),
                ('medicines', models.CharField(max_length=750)),
                ('preventions', models.CharField(max_length=750)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=750)),
                ('First_name', models.CharField(max_length=750)),
                ('Last_name', models.CharField(max_length=750)),
                ('Email', models.EmailField(max_length=750)),
            ],
        ),
    ]
